const express=require('express');
const session=require('express-session');
const multer=require('multer');
const {Pool}=require('pg');
const {v2:cloudinary}=require('cloudinary');
const path=require('path');

const app=express();
const PORT=process.env.PORT||3000;

if(!process.env.DATABASE_URL){console.warn('WARNING: DATABASE_URL is not set. Add your Supabase Session Pooler connection string in Render Environment Variables.');}
const pool=new Pool({
  connectionString:process.env.DATABASE_URL,
  ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:undefined,
  max:5,
  idleTimeoutMillis:30000,
  connectionTimeoutMillis:10000
});

app.use(express.json({limit:'2mb'}));
app.use(express.urlencoded({extended:true}));
app.use(session({secret:process.env.SESSION_SECRET||'dev-secret-change-me',resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'lax'}}));
app.use(express.static(path.join(__dirname,'public')));

cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET});
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(jpeg|png|webp|gif)$/.test(file.mimetype))});

const money=n=>'৳'+Number(n).toLocaleString('en-BD');

async function initDb(){
  await pool.query(`
    CREATE TABLE IF NOT EXISTS public.products(
      id bigint generated by default as identity primary key,
      name text not null,
      category text not null,
      price integer not null,
      old_price integer default 0,
      icon text default '🛍️',
      image_url text default '',
      stock integer default 0,
      active integer default 1,
      created_at timestamptz default now()
    );
    CREATE TABLE IF NOT EXISTS public.orders(
      id bigint generated by default as identity primary key,
      customer_name text not null,
      phone text not null,
      address text not null,
      payment text not null,
      note text,
      items_json text not null,
      total integer not null,
      status text default 'Pending',
      created_at timestamptz default now()
    );
  `);
  const {rows}=await pool.query('SELECT COUNT(*)::int AS c FROM public.products');
  if(rows[0].c===0){
    const seed=[
      ['Classic Oversized T-Shirt','Fashion',790,990,'👕','',25],
      ['Premium Smart Watch','Electronics',2490,2990,'⌚','',12],
      ['Wireless Headphones','Electronics',1890,2290,'🎧','',18],
      ['Minimal Leather Bag','Accessories',1590,1990,'👜','',10],
      ['Modern Table Lamp','Home',1190,1490,'💡','',20],
      ['Everyday Sneakers','Fashion',2190,2590,'👟','',15],
      ['Ceramic Coffee Set','Home',890,1090,'☕','',30],
      ['Classic Sunglasses','Accessories',990,1290,'🕶️','',14]
    ];
    for(const x of seed) await pool.query('INSERT INTO public.products(name,category,price,old_price,icon,image_url,stock) VALUES($1,$2,$3,$4,$5,$6,$7)',x);
  }
  console.log('Database ready.');
}

app.get('/api/products',async(req,res)=>{
  try{const {rows}=await pool.query('SELECT * FROM public.products WHERE active=1 ORDER BY id DESC');res.json(rows)}
  catch(e){console.error(e);res.status(500).json({error:'Unable to load products.'})}
});

app.post('/api/orders',async(req,res)=>{
  const {customer_name,phone,address,payment,note,items}=req.body;
  if(!customer_name||!phone||!address||!payment||!Array.isArray(items)||!items.length)return res.status(400).json({error:'Please complete all required fields.'});
  const client=await pool.connect();
  try{
    await client.query('BEGIN');
    let total=0,normalized=[];
    for(const i of items){
      const {rows}=await client.query('SELECT * FROM public.products WHERE id=$1 AND active=1 FOR UPDATE',[i.id]);
      const p=rows[0]; const qty=Math.max(1,Math.floor(Number(i.qty)||1));
      if(!p)throw new Error('A product is unavailable.');
      if(Number(p.stock)<qty)throw new Error(`Only ${p.stock} units of ${p.name} are available.`);
      total+=Number(p.price)*qty; normalized.push({id:p.id,name:p.name,price:p.price,qty});
    }
    const order=await client.query('INSERT INTO public.orders(customer_name,phone,address,payment,note,items_json,total) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[customer_name,phone,address,payment,note||'',JSON.stringify(normalized),total]);
    for(const i of normalized)await client.query('UPDATE public.products SET stock=stock-$1 WHERE id=$2',[i.qty,i.id]);
    await client.query('COMMIT');
    res.json({ok:true,order_id:order.rows[0].id,total,money:money(total)});
  }catch(e){await client.query('ROLLBACK');res.status(400).json({error:e.message||'Could not place order.'})}
  finally{client.release()}
});

function admin(req,res,next){if(req.session.admin)return next();res.status(401).json({error:'Admin login required.'})}
app.post('/api/admin/login',(req,res)=>{const u=process.env.ADMIN_USER||'admin',p=process.env.ADMIN_PASSWORD||'admin123';if(req.body.username===u&&req.body.password===p){req.session.admin=true;return res.json({ok:true})}res.status(401).json({error:'Invalid login.'})});
app.post('/api/admin/logout',(req,res)=>req.session.destroy(()=>res.json({ok:true})));
app.get('/api/admin/me',(req,res)=>res.json({loggedIn:!!req.session.admin}));
app.get('/api/admin/orders',admin,async(req,res)=>{try{const {rows}=await pool.query('SELECT * FROM public.orders ORDER BY id DESC');res.json(rows.map(o=>({...o,items:JSON.parse(o.items_json)})))}catch(e){res.status(500).json({error:'Unable to load orders.'})}});
app.patch('/api/admin/orders/:id',admin,async(req,res)=>{const allowed=['Pending','Confirmed','Packed','Shipped','Delivered','Cancelled'];if(!allowed.includes(req.body.status))return res.status(400).json({error:'Invalid status'});try{await pool.query('UPDATE public.orders SET status=$1 WHERE id=$2',[req.body.status,req.params.id]);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});

function uploadToCloudinary(file){return new Promise((resolve,reject)=>{if(!process.env.CLOUDINARY_CLOUD_NAME||!process.env.CLOUDINARY_API_KEY||!process.env.CLOUDINARY_API_SECRET)return reject(new Error('Cloudinary is not configured.'));const stream=cloudinary.uploader.upload_stream({folder:'grameen-shop/products',resource_type:'image'},(error,result)=>error?reject(error):resolve(result.secure_url));stream.end(file.buffer)})}

app.post('/api/admin/products',admin,upload.single('image'),async(req,res)=>{
  try{
    const {name,category,price,old_price,icon,stock}=req.body;
    if(!name||!category||!price)return res.status(400).json({error:'Name, category and price are required.'});
    let image_url='';if(req.file)image_url=await uploadToCloudinary(req.file);
    const r=await pool.query('INSERT INTO public.products(name,category,price,old_price,icon,image_url,stock) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[name,category,Number(price),Number(old_price||0),icon||'🛍️',image_url,Number(stock||0)]);
    res.json({ok:true,id:r.rows[0].id,image_url});
  }catch(err){res.status(400).json({error:err.message||'Image upload failed.'})}
});

app.patch('/api/admin/products/:id',admin,upload.single('image'),async(req,res)=>{
  try{
    const old=await pool.query('SELECT * FROM public.products WHERE id=$1',[req.params.id]);if(!old.rows[0])return res.status(404).json({error:'Not found'});
    const p=old.rows[0],x={...p,...req.body};let image_url=x.image_url||p.image_url||'';if(req.file)image_url=await uploadToCloudinary(req.file);
    await pool.query('UPDATE public.products SET name=$1,category=$2,price=$3,old_price=$4,icon=$5,image_url=$6,stock=$7,active=$8 WHERE id=$9',[x.name,x.category,Number(x.price),Number(x.old_price||0),x.icon||'🛍️',image_url,Number(x.stock||0),String(x.active)==='1'||x.active===true?1:0,req.params.id]);
    res.json({ok:true,image_url});
  }catch(err){res.status(400).json({error:err.message||'Image update failed.'})}
});
app.delete('/api/admin/products/:id',admin,async(req,res)=>{try{await pool.query('UPDATE public.products SET active=0 WHERE id=$1',[req.params.id]);res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});

app.use((err,req,res,next)=>{if(err instanceof multer.MulterError)return res.status(400).json({error:err.code==='LIMIT_FILE_SIZE'?'Image must be 5MB or smaller.':err.message});if(err)return res.status(400).json({error:err.message||'Request failed.'});next()});

initDb().then(()=>app.listen(PORT,()=>console.log(`Grameen Shop running on port ${PORT}`))).catch(err=>{console.error('Database initialization failed:',err);process.exit(1)});
